// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEpkfleQlSH7hV4JZ2WgReyrSHfEmskvw',
    appId: '1:676429635352:web:8a003e45777938ecf2486d',
    messagingSenderId: '676429635352',
    projectId: 'codeyou-e43a7',
    authDomain: 'codeyou-e43a7.firebaseapp.com',
    storageBucket: 'codeyou-e43a7.appspot.com',
    measurementId: 'G-YK32Z1TMF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByozA7Bg12Ugyc-vLI1eugy-0iXODKExo',
    appId: '1:676429635352:android:0db56a8f8b620054f2486d',
    messagingSenderId: '676429635352',
    projectId: 'codeyou-e43a7',
    storageBucket: 'codeyou-e43a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb4BP3Co8509oZRksnx5i6U1XtvX0MCnA',
    appId: '1:676429635352:ios:374ae17ed8d15ee9f2486d',
    messagingSenderId: '676429635352',
    projectId: 'codeyou-e43a7',
    storageBucket: 'codeyou-e43a7.appspot.com',
    iosBundleId: 'com.example.codeyou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb4BP3Co8509oZRksnx5i6U1XtvX0MCnA',
    appId: '1:676429635352:ios:39395d35f5ca0a76f2486d',
    messagingSenderId: '676429635352',
    projectId: 'codeyou-e43a7',
    storageBucket: 'codeyou-e43a7.appspot.com',
    iosBundleId: 'com.example.codeyou.RunnerTests',
  );
}
